name: Spawn-Plugin
main: spawn\main
version: 0.0.1
api: 3.0.0
author: SecroMC

commands:
  
  spawn:
    description: Vous téléporte au spawn
  
  setspawn:
    description: Définir le spawn principal
    permission: setspawn.use
